server:
  port: 9003
#  servlet:
#    context-path: /book

spring:
  datasource:
    name: tools # 数据库名称
    username: root
    password: 123456
#    password: 2Fm77109_
    url: jdbc:mysql://localhost:3306/tools?serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
#  mapper-locations: classpath:com/byr/tools/mapper/*Mapper.xml  # 对应mapper映射xml文件的所在路径
#  type-aliases-package: com.byr.tools.entity  # 对应实体类的路径

#mybatis plus配置
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#      field-strategy: not_empty
#      # 驼峰下划线转换
#      column-underline: false
#      # 逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      db-type: mysql
#    refresh: false
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: false
#  mapper-locations: classpath:com/byr/tools/mapper/*Mapper.xml  # 对应mapper映射xml文件的所在路径
#  type-aliases-package: com.byr.tools.entity  # 对应实体类的路径
#  typeEnumsPackage: com.byr.tools.entity.enums
#  mybatis-plus.configuration.map-underscore-to-camel-case: false

#mybatis plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:com/byr/tools/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.byr.tools.entity
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.byr.tools.entity.enums
  global-config:
    #    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
#    #驼峰下划线转换
#    db-column-underline: true
#    #mp2.3+ 全局表前缀 mp_
#    table-prefix: mp_
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    capital-mode: true
#    #Sequence序列接口实现类配置
#    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    #自定义填充策略接口实现
  #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    # 控制台输出数据库执行语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    #    map-underscore-to-camel-case: true
    cache-enabled: true
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'

# 控制台输出sql语句
#logging:
#  level:
#    com:
#      byr:
#        bookshop:
#          mapper: debug